// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDkxrIUWGdeXoVXU2ClmhRD4_g76vv9M',
    appId: '1:965615603956:web:220438c66d2b66b15c8ea1',
    messagingSenderId: '965615603956',
    projectId: 'k24-klik-redesign',
    authDomain: 'k24-klik-redesign.firebaseapp.com',
    storageBucket: 'k24-klik-redesign.firebasestorage.app',
    measurementId: 'G-BTB42PQZMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjx0kw_106IXbPsTR0FlkGPwVssOpdww',
    appId: '1:965615603956:android:522f7771b5c94f355c8ea1',
    messagingSenderId: '965615603956',
    projectId: 'k24-klik-redesign',
    storageBucket: 'k24-klik-redesign.firebasestorage.app',
  );
}
